language: scala
sudo: true
dist: trusty
addons:
  apt:
    packages:
    - numactl
    - libnuma1
    - libnuma-dev
    - libnuma-dbg
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/ssl
  - $HOME/mongodb-linux-x86_64-amazon-3.4.5
env:
  - _DISABLED=true
matrix:
  include:
  - env: RELEASE_SUFFIX=play25 PLAY_VERSION=2.5.11 PUBLISHABLE=yes
    jdk: oraclejdk8
    scala: 2.11.12
  - env: RELEASE_SUFFIX=play26 PLAY_VERSION=2.6.7 PUBLISHABLE=yes
    jdk: oraclejdk8
    scala: 2.12.10
  - env: RELEASE_SUFFIX=play27 PLAY_VERSION=2.7.4 PUBLISHABLE=yes
    jdk: oraclejdk9
    scala: 2.13.1
before_install: ./.ci_scripts/beforeInstall.sh
script: ./.ci_scripts/validate.sh
after_success:
- export CI_BRANCH=$TRAVIS_BRANCH SCALA_VERSION=$TRAVIS_SCALA_VERSION
- test '!' "v$RELEASE_SUFFIX" = "vplay25" && export CROSS_SCALA_VERSIONS=yes
- ./.ci_scripts/afterSuccess.sh
